In [1]:
import random
import psycopg2
from calendar import monthrange
import requests
import time
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
import pandas as pd
import numpy as np
import time
import math
import copy

In [2]:
total_region=[]
total_ob=[]

In [3]:
def GET_UA():
    uastrings = ["Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36",\
                "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.72 Safari/537.36",\
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25",\
                "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0",\
                "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36",\
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36",\
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10",\
                "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",\
                "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0",\
                "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36"\
                ]
    return random.choice(uastrings)

In [4]:
def getData(year,month,day,hour,minute,code):
    final_data = []
    try:
        session = requests.Session()
        retry = Retry(connect=5, backoff_factor=0.5)
        adapter = HTTPAdapter(max_retries=retry)
        session.mount('http://', adapter)
        session.mount('https://', adapter)
        headers = {'User-Agent': GET_UA()}   
        URL = "https://intermagnet.org/data-donnee/dataplot-1-eng.php?year="+str(year)+"&month="+str(month)+"&day="+str(day)+"&start_hour="+str(hour)+"&end_hour="+str(hour+1)+"&filter_region%5B%5D=America&filter_region%5B%5D=Asia&filter_region%5B%5D=Europe&filter_region%5B%5D=Pacific&filter_region%5B%5D=Africa&filter_lat%5B%5D=NH&filter_lat%5B%5D=NM&filter_lat%5B%5D=E&filter_lat%5B%5D=SM&filter_lat%5B%5D=SH&sort=iaga&iaga_code="+code+"&type=xyz&fixed_scale=1&format=html"
        r =  session.get(URL, headers=headers) 
        soup = BeautifulSoup(r.content, 'html.parser')
        table = soup.find(lambda tag: tag.name=='table')
        time_s = []
        for tt in [year, month, day, hour, minute]:
            if(tt<10):
                temp = '0'+str(tt)
            else:
                temp = str(tt)
            time_s.append(temp)
        time_check = time_s[0]+'-'+time_s[1]+'-'+time_s[2]+' '+time_s[3]+':'+time_s[4]+':00'
        print(time_check)
        try:
            rows = table.findAll(lambda tag: tag.name=='tr')
            for row in rows:
                cols = row.findAll('td')
                try :
                    if (cols[0]!=None):
                        if(str(cols[0].text) == time_check):
                            print(time_check)
                            final_data.extend([str(cols[0].text),cols[1].text,cols[2].text,cols[3].text,cols[4].text, code])
                except Exception as err:
                    print(err)
                    pass
            return final_data
            print("Data Saved")
        except:
            print('Data not present')
            pass
    except requests.exceptions.RequestException as e:
        print(e)
        time.sleep(300)
    except requests.ConnectionError as e:
        print("OOPS!! Connection Error. Make sure you are connected to Internet. Technical Details given below.\n")
        print(str(e))            
        renewIPadress()       
    except requests.Timeout as e:
        print("OOPS!! Timeout Error")
        print(str(e))
        renewIPadress()       
    except requests.RequestException as e:
        print("OOPS!! General Error")
        print(str(e))
        renewIPadress()
    except KeyboardInterrupt:
        print("Someone closed the program")

In [16]:
def getRegions(connection):
    print('getting list of Regions')
    cursor = connection.cursor()
    postgreSQL_select_Query = "select id,region_name,region_api from public.data_region"
    cursor.execute(postgreSQL_select_Query)
    regions = cursor.fetchall()
    return regions
def getObs(connection,region_id,year):
#     print('getting Observaratory based on regionid'+str(region_id))
    cursor = connection.cursor()
    postgreSQL_select_Query = "select code,station_name,year,id,lat,lon FROM public.data_observatory where year="+str(year)+" and region_id="+str(region_id)
    cursor.execute(postgreSQL_select_Query)
    regions = cursor.fetchall()
    return regions

In [13]:
def get_obs(oobs, lat = 27.3314, lon = 88.6138):
    
    dist = 360
    code = ''
    cname = ''
    for i in oobs:
        x, y = lon, lat
        x1, y1 = float(i[5]), float(i[4])
        temp = math.sqrt((x-x1)**2 + (y-y1)**2)
        if temp < dist:
            dist = temp
            code = i[0]
            cname = i[1]
    if code == '':
        print('Cannot Access Region Code')
    else:
        return code

In [15]:
year = 2019
month = 1
day = 1
hour = 0
minute = 20

# count = 1
# ob = pd.read_csv('note1.csv')
# ob_list = ob['code']
t0 = time.clock()
connection = psycopg2.connect(user="postgres",
                              password="@#bedrock$203",
                              host="1.7.151.13",
                              port="5432",
                              database="cosmosis")

regions=getRegions(connection)
oobs = [] 
for region in regions:
#        print(region)

    region_id=region[0]
    region_name=region[1]
    region_api=region[2]
#     print(region_id,', ', region_name,', ', region_api)
    obs=getObs(connection, region_id, year) 
    for ob in obs:
        code=ob[0]
        ob_name=ob[1]
        year=ob[2]
        obj_id=ob[3]
        lat=float(ob[4])
        if (float(ob[5])>180):
            lon = float(ob[5]) - 360
        else:
            lon=ob[5]
        #print(code,', ', ob_name,', ', year,', ', obj_id,', ', lat,', ', lon)
        oobs.append([code, ob_name, year, obj_id, lat, lon])
code = get_obs(oobs, lat = -27.3314, lon = -88.6138)
datess = getData(year,month,day,hour,minute,code)
t1 = time.clock()
timespan = t1 - t0
print('Time period:', timespan)
print('Data',datess)

c:\python3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.

getting list of Regions
getting Observaratory based on regionid1
getting Observaratory based on regionid2
getting Observaratory based on regionid3
getting Observaratory based on regionid4
getting Observaratory based on regionid5
2019-01-01 00:20:00
list index out of range
2019-01-01 00:20:00
Time period: 2.6281936000000314
Data ['2019-01-01 00:20:00', '24873.30', '-1195.80', '-381.30', '24904.90', 'HUA']

c:\python3\lib\site-packages\ipykernel_launcher.py:41: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead

In [5]:
ob = pd.read_csv('note1.csv')
ob_list = ob['code']
for i in ob_list:
    print(i)

ABG
ABK
AIA
AMS
API
ARS
ASC
ASP
BDV
BEL
BFO
BLC
BMT
BOU
BOX
BRD
BRW
BSL
CBB
CKI
CLF
CMO
CNB
CPL
CSY
CYG
CZT
DED
DLT
DMC
DOU
DRV
DUR
EBR
ESK
EYR
FCC
FRD
FRN
FUR
GAN
GCK
GDH
GNG
GUA
GUI
HAD
HBK
HER
HLP
HON
HRB
HRN
HUA
HYB
IPM
IQA
IRT
IZN
JAI
JCO
KAK
KDU
KEP
KHB
KMH
KNY
KOU
LER
LON
LRM
LVV
LYC
MAB
MAW
MCQ
MEA
MGD
MMB
NAQ
NEW
NGK
NUR
NVS
ORC
OTT
PAG
PEG
PET
PHU
PIL
PPT
PST
RES
SBA
SBL
SFS
SHE
SHU
SIT
SJG
SOD
SON
SPG
SPT
STJ
SUA
TAM
TDC
THL
THY
TSU
TTB
TUC
UPS
VAL
VIC
VNA
VOS
VSS
WIC
WNG
YAK

In [ ]:
print(timespan/60)

In [ ]:
print(((11*365)/60)/24)

In [6]:
data_o = pd.read_csv("note1.csv")
data_o

    code                                      obs_name       coordinates
0    ABG                                        Alibag       18.62/72.87
1    ABK                                        Abisko     68.358/18.823
2    AIA   Argentine Islands (Akademik Vernadsky base)     -65.25/295.75
3    AMS             Martin de Vivies-Amsterdam Island       -37.8/77.57
4    API                                          Apia      -13.8/188.22
..   ...                                           ...               ...
118  VOS                                        Vostok   -78.464/106.835
119  VSS                                     Vassouras      -22.4/316.35
120  WIC                            Conrad Observatory   47.9305/15.8657
121  WNG                                        Wingst        53.74/9.07
122  YAK                                       Yakutsk      61.96/129.66

[123 rows x 3 columns]

In [7]:
oobs = data_o.values.tolist()
for obs in oobs:
    obs[2] = obs[2].split('/')
    obs[2][0], obs[2][1] = float(obs[2][0]), float(obs[2][1])
    if obs[2][1]>180:
        obs[2][1] = obs[2][1] - 360
oobs

[['ABG', ' Alibag', [18.62, 72.87]],
 ['ABK', ' Abisko', [68.358, 18.823]],
 ['AIA', ' Argentine Islands (Akademik Vernadsky base)', [-65.25, -64.25]],
 ['AMS', ' Martin de Vivies-Amsterdam Island', [-37.8, 77.57]],
 ['API', ' Apia', [-13.8, -171.78]],
 ['ARS', ' Arti', [56.433, 58.567]],
 ['ASC', ' Ascension Island', [-7.95, -14.379999999999995]],
 ['ASP', ' Alice Springs', [-23.77, 133.88]],
 ['BDV', ' Budkov', [49.08, 14.02]],
 ['BEL', ' Belsk', [51.836, 20.789]],
 ['BFO', ' Black Forest', [48.331, 8.325]],
 ['BLC', ' Baker Lake', [64.318, -96.012]],
 ['BMT', ' Beijing Ming Tombs', [40.3, 116.2]],
 ['BOU', ' Boulder', [40.14, -105.24000000000001]],
 ['BOX', ' Borok', [58.07, 38.23]],
 ['BRD', ' Brandon', [49.87, -99.97390000000001]],
 ['BRW', ' Barrow', [71.32, -156.62]],
 ['BSL', ' Stennis Space Center', [30.35, -89.63999999999999]],
 ['CBB', ' Cambridge Bay', [69.123, -105.031]],
 ['CKI', ' Cocos-Keeling Islands', [-12.1875, 96.8336]],
 ['CLF', ' Chambon la Foret', [48.02, 2.27]],
 ['CMO', ' College', [64.87, -147.86]],
 ['CNB', ' Canberra', [-35.32, 149.36]],
 ['CPL', ' Choutuppal', [17.2935, 78.9192]],
 ['CSY', ' Casey Station', [-66.283, 110.533]],
 ['CYG', ' Cheongyang', [36.37, 126.854]],
 ['CZT', ' Port Alfred', [-46.43, 51.87]],
 ['DED', ' Deadhorse', [70.36, -148.79]],
 ['DLT', ' Dalat', [11.94, 108.48]],
 ['DMC', ' Dome C', [-75.25, 124.167]],
 ['DOU', ' Dourbes', [50.1, 4.6]],
 ['DRV', " Dumont d'Urville", [-66.67, 140.01]],
 ['DUR', ' Duronia', [41.35, 14.466]],
 ['EBR', ' Ebro', [40.957, 0.333]],
 ['ESK', ' Eskdalemuir', [55.32, -3.1999999999999886]],
 ['EYR', ' Eyrewell', [-43.474, 172.393]],
 ['FCC', ' Fort Churchill', [58.759, -94.08800000000002]],
 ['FRD', ' Fredericksburg', [38.2, -77.37]],
 ['FRN', ' Fresno', [37.09, -119.72]],
 ['FUR', ' Furstenfeldbruck', [48.17, 11.28]],
 ['GAN', ' Gan', [0.6946, 73.1537]],
 ['GCK', ' Grocka', [44.6, 20.8]],
 ['GDH', ' Qeqertarsuaq (Godhavn)', [69.252, -53.533000000000015]],
 ['GNG', ' Gingin', [-31.356, 115.715]],
 ['GUA', ' Guam', [13.59, 144.87]],
 ['GUI', ' Guimar-Tenerife', [28.32, -16.430000000000007]],
 ['HAD', ' Hartland', [51.0, -4.480000000000018]],
 ['HBK', ' Hartebeesthoek', [-25.88, 27.71]],
 ['HER', ' Hermanus', [-34.43, 19.23]],
 ['HLP', ' Hel', [54.603, 18.811]],
 ['HON', ' Honolulu', [21.32, -158.0]],
 ['HRB', ' Hurbanovo', [47.86, 18.19]],
 ['HRN', ' Hornsund', [77.002, 15.547]],
 ['HUA', ' Huancayo', [-12.05, -75.32999999999998]],
 ['HYB', ' Hyderabad', [17.4, 78.6]],
 ['IPM',
  ' Isla de Pascua Mataveri (Easter Island)',
  [-27.2, -109.41999999999999]],
 ['IQA', ' Iqaluit', [63.753, -68.51799999999997]],
 ['IRT', ' Irkutsk', [52.27, 104.45]],
 ['IZN', ' Iznik', [40.5, 29.72]],
 ['JAI', ' Jaipur', [26.92, 75.8]],
 ['JCO', ' Jim Carrigan Observatory', [70.356, -148.799]],
 ['KAK', ' Kakioka', [36.23, 140.18]],
 ['KDU', ' Kakadu', [-12.69, 132.47]],
 ['KEP', ' King Edward Point', [-54.2821, -36.49290000000002]],
 ['KHB', ' Khabarovsk', [47.61, 134.69]],
 ['KMH', ' Keetmanshoop', [-26.54, 18.11]],
 ['KNY', ' Kanoya', [31.42, 130.88]],
 ['KOU', ' Kourou', [5.21, -52.73000000000002]],
 ['LER', ' Lerwick', [60.13, -1.1800000000000068]],
 ['LON', ' Lonjsko Polje', [45.4081, 16.6592]],
 ['LRM', ' Learmonth', [-22.22, 114.1]],
 ['LVV', ' Lviv', [49.9, 23.75]],
 ['LYC', ' Lycksele', [64.6, 18.8]],
 ['MAB', ' Manhay', [50.298, 5.682]],
 ['MAW', ' Mawson', [-67.6, 62.88]],
 ['MCQ', ' Macquarie Island', [-54.5, 158.95]],
 ['MEA', ' Meanook', [54.616, -113.34700000000001]],
 ['MGD', ' Magadan', [60.051, 150.728]],
 ['MMB', ' Memambetsu', [43.91, 144.19]],
 ['NAQ', ' Narsarsuaq', [61.16, -45.44200000000001]],
 ['NEW', ' Newport', [48.27, -117.12]],
 ['NGK', ' Niemegk', [52.07, 12.68]],
 ['NUR', ' Nurmijarvi', [60.51, 24.66]],
 ['NVS', ' Novosibirsk', [54.85, 83.23]],
 ['ORC', ' Orcadas', [-60.737, -44.74000000000001]],
 ['OTT', ' Ottawa', [45.403, -75.55200000000002]],
 ['PAG', ' Panagjurishte', [42.5, 24.2]],
 ['PEG', ' Pedeli', [38.1, 23.9]],
 ['PET', ' Paratunka', [52.971, 158.248]],
 ['PHU', ' Phuthuy', [21.03, 105.95]],
 ['PIL', ' Pilar', [-31.4, -63.879999999999995]],
 ['PPT', ' Pamatai', [-17.57, -149.58]],
 ['PST', ' Port Stanley', [-51.7, -57.889999999999986]],
 ['RES', ' Resolute Bay', [74.69, -94.89499999999998]],
 ['SBA', ' Scott Base', [-77.85, 166.78]],
 ['SBL', ' Sable Island', [43.9321, -60.0095]],
 ['SFS', ' San Fernando', [36.667, -5.944999999999993]],
 ['SHE', ' Saint Helena', [-15.961, -5.747000000000014]],
 ['SHU', ' Shumagin', [55.35, -160.46]],
 ['SIT', ' Sitka', [57.06, -135.33]],
 ['SJG', ' San Juan', [18.11, -66.14999999999998]],
 ['SOD', ' Sodankyla', [67.37, 26.63]],
 ['SON', ' Sonmiani', [25.1168, 66.4487]],
 ['SPG', ' Saint Petersburg', [60.542, 29.716]],
 ['SPT', ' San Pablo-Toledo', [39.55, -4.350000000000023]],
 ['STJ', " St John's", [47.595, -52.67700000000002]],
 ['SUA', ' Surlari', [44.68, 26.25]],
 ['TAM', ' Tamanrasset', [22.79, 5.53]],
 ['TDC', ' Tristan da Cunha', [-37.067, -12.314999999999998]],
 ['THL', ' Qaanaaq (Thule)', [77.47, -69.22699999999998]],
 ['THY', ' Tihany', [46.9, 17.89]],
 ['TSU', ' Tsumeb', [-19.202, 17.584]],
 ['TTB', ' Tatuoca', [-1.205, -48.51299999999998]],
 ['TUC', ' Tucson', [32.18, -110.72999999999999]],
 ['UPS', ' Uppsala', [59.903, 17.353]],
 ['VAL', ' Valentia', [51.933, -10.25]],
 ['VIC', ' Victoria', [48.52, -123.41999999999999]],
 ['VNA', ' Neumayer Station â…¢', [-70.683, -8.281999999999982]],
 ['VOS', ' Vostok', [-78.464, 106.835]],
 ['VSS', ' Vassouras', [-22.4, -43.64999999999998]],
 ['WIC', ' Conrad Observatory', [47.9305, 15.8657]],
 ['WNG', ' Wingst', [53.74, 9.07]],
 ['YAK', ' Yakutsk', [61.96, 129.66]]]

In [8]:
oobs[100][1]

' San Juan'

[['BLC', ' Baker Lake', 2019, 2824, 64.318, -96.012],
 ['BOU', ' Boulder', 2019, 2825, 40.14, -105.24000000000001],
 ['BRD', ' Brandon', 2019, 2826, 49.87, -99.97390000000001],
 ['BRW', ' Barrow', 2019, 2827, 71.32, -156.62],
 ['BSL', ' Stennis Space Center', 2019, 2828, 30.35, -89.63999999999999],
 ['CBB', ' Cambridge Bay', 2019, 2829, 69.123, -105.031],
 ['CMO', ' College', 2019, 2830, 64.87, -147.86],
 ['DED', ' Deadhorse', 2019, 2831, 70.36, -148.79],
 ['FCC', ' Fort Churchill', 2019, 2832, 58.759, -94.08800000000002],
 ['FRD', ' Fredericksburg', 2019, 2833, 38.2, -77.37],
 ['FRN', ' Fresno', 2019, 2834, 37.09, -119.72],
 ['GDH', ' Qeqertarsuaq (Godhavn)', 2019, 2835, 69.252, -53.533000000000015],
 ['HUA', ' Huancayo', 2019, 2836, -12.05, -75.32999999999998],
 ['IQA', ' Iqaluit', 2019, 2837, 63.753, -68.51799999999997],
 ['JCO', ' Jim Carrigan Observatory', 2019, 2838, 70.356, -148.799],
 ['KEP', ' King Edward Point', 2019, 2839, -54.2821, -36.49290000000002],
 ['KOU', ' Kourou', 2019, 2840, 5.21, -52.73000000000002],
 ['MEA', ' Meanook', 2019, 2841, 54.616, -113.34700000000001],
 ['NAQ', ' Narsarsuaq', 2019, 2842, 61.16, -45.44200000000001],
 ['NEW', ' Newport', 2019, 2843, 48.27, -117.12],
 ['ORC', ' Orcadas', 2019, 2844, -60.737, -44.74000000000001],
 ['OTT', ' Ottawa', 2019, 2845, 45.403, -75.55200000000002],
 ['PIL', ' Pilar', 2019, 2846, -31.4, -63.879999999999995],
 ['PST', ' Port Stanley', 2019, 2847, -51.7, -57.889999999999986],
 ['RES', ' Resolute Bay', 2019, 2848, 74.69, -94.89499999999998],
 ['SBL', ' Sable Island', 2019, 2849, 43.9321, -60.0095],
 ['SHU', ' Shumagin', 2019, 2850, 55.35, -160.46],
 ['SIT', ' Sitka', 2019, 2851, 57.06, -135.33],
 ['SJG', ' San Juan', 2019, 2852, 18.11, -66.14999999999998],
 ['STJ', " St John's", 2019, 2853, 47.595, -52.67700000000002],
 ['THL', ' Qaanaaq (Thule)', 2019, 2854, 77.47, -69.22699999999998],
 ['TUC', ' Tucson', 2019, 2855, 32.18, -110.72999999999999],
 ['VIC', ' Victoria', 2019, 2856, 48.52, -123.41999999999999],
 ['VSS', ' Vassouras', 2019, 2857, -22.4, -43.64999999999998],
 ['YKC', ' Yellowknife', 2019, 2858, 62.48, -114.482],
 ['AAA', ' Alma Ata', 2019, 2859, 43.2, '76.9'],
 ['ABG', ' Alibag', 2019, 2860, 18.62, '72.87'],
 ['ARS', ' Arti', 2019, 2861, 56.433, '58.567'],
 ['BMT', ' Beijing Ming Tombs', 2019, 2862, 40.3, '116.2'],
 ['CYG', ' Cheongyang', 2019, 2863, 36.37, '126.854'],
 ['DLT', ' Dalat', 2019, 2864, 11.94, '108.48'],
 ['HYB', ' Hyderabad', 2019, 2865, 17.4, '78.6'],
 ['IRT', ' Irkutsk', 2019, 2866, 52.27, '104.45'],
 ['JAI', ' Jaipur', 2019, 2867, 26.92, '75.80'],
 ['KAK', ' Kakioka', 2019, 2868, 36.23, '140.18'],
 ['KHB', ' Khabarovsk', 2019, 2869, 47.61, '134.69'],
 ['KNY', ' Kanoya', 2019, 2870, 31.42, '130.88'],
 ['LZH', ' Lanzhou', 2019, 2871, 36.1, '103.84'],
 ['MGD', ' Magadan', 2019, 2872, 60.051, '150.728'],
 ['MMB', ' Memambetsu', 2019, 2873, 43.91, '144.19'],
 ['NVS', ' Novosibirsk', 2019, 2874, 54.85, '83.23'],
 ['PET', ' Paratunka', 2019, 2875, 52.971, '158.248'],
 ['PHU', ' Phuthuy', 2019, 2876, 21.03, '105.95'],
 ['SON', ' Sonmiani', 2019, 2877, 25.1168, '66.4487'],
 ['AMS', ' Martin de Vivies-Amsterdam Island', 2019, 2935, -37.8, '77.57'],
 ['ASC', ' Ascension Island', 2019, 2936, -7.95, -14.379999999999995],
 ['CZT', ' Port Alfred', 2019, 2937, -46.43, '51.87'],
 ['HBK', ' Hartebeesthoek', 2019, 2938, -25.88, '27.71'],
 ['HER', ' Hermanus', 2019, 2939, -34.43, '19.23'],
 ['KMH', ' Keetmanshoop', 2019, 2940, -26.54, '18.110'],
 ['PAF', ' Port-aux-Francais', 2019, 2941, -49.35, '70.26'],
 ['TAM', ' Tamanrasset', 2019, 2942, 22.79, '5.53'],
 ['TSU', ' Tsumeb', 2019, 2943, -19.202, '17.584'],
 ['ABK', ' Abisko', 2019, 2878, 68.358, '18.823'],
 ['BDV', ' Budkov', 2019, 2879, 49.08, '14.02'],
 ['BEL', ' Belsk', 2019, 2880, 51.836, '20.789'],
 ['BFO', ' Black Forest', 2019, 2881, 48.331, '8.325'],
 ['BOX', ' Borok', 2019, 2882, 58.07, '38.23'],
 ['CLF', ' Chambon la Foret', 2019, 2883, 48.02, '2.27'],
 ['DOU', ' Dourbes', 2019, 2884, 50.1, '4.6'],
 ['DUR', ' Duronia', 2019, 2885, 41.35, '14.466'],
 ['EBR', ' Ebro', 2019, 2886, 40.957, '0.333'],
 ['ESK', ' Eskdalemuir', 2019, 2887, 55.32, -3.1999999999999886],
 ['FUR', ' Furstenfeldbruck', 2019, 2888, 48.17, '11.28'],
 ['GCK', ' Grocka', 2019, 2889, 44.6, '20.8'],
 ['GUI', ' Guimar-Tenerife', 2019, 2890, 28.32, -16.430000000000007],
 ['HAD', ' Hartland', 2019, 2891, 51.0, -4.480000000000018],
 ['HLP', ' Hel', 2019, 2892, 54.603, '18.811'],
 ['HRB', ' Hurbanovo', 2019, 2893, 47.86, '18.19'],
 ['HRN', ' Hornsund', 2019, 2894, 77.002, '15.547'],
 ['KIV', ' Kiev', 2019, 2895, 50.72, '30.3'],
 ['LER', ' Lerwick', 2019, 2896, 60.13, -1.1800000000000068],
 ['LON', ' Lonjsko Polje', 2019, 2897, 45.4081, '16.6592'],
 ['LVV', ' Lviv', 2019, 2898, 49.9, '23.75'],
 ['LYC', ' Lycksele', 2019, 2899, 64.6, '18.8'],
 ['MAB', ' Manhay', 2019, 2900, 50.298, '5.682'],
 ['NCK', ' Nagycenk', 2019, 2901, 47.63, '16.72'],
 ['NGK', ' Niemegk', 2019, 2902, 52.07, '12.68'],
 ['PAG', ' Panagjurishte', 2019, 2903, 42.5, '24.2'],
 ['PEG', ' Pedeli', 2019, 2904, 38.1, '23.9'],
 ['SFS', ' San Fernando', 2019, 2905, 36.667, -5.944999999999993],
 ['SOD', ' Sodankyla', 2019, 2906, 67.37, '26.63'],
 ['SPG', ' Saint Petersburg', 2019, 2907, 60.542, '29.716'],
 ['SPT', ' San Pablo-Toledo', 2019, 2908, 39.55, -4.350000000000023],
 ['SUA', ' Surlari', 2019, 2909, 44.68, '26.25'],
 ['THY', ' Tihany', 2019, 2910, 46.9, '17.89'],
 ['UPS', ' Uppsala', 2019, 2911, 59.903, '17.353'],
 ['WIC', ' Conrad Observatory', 2019, 2912, 47.9305, '15.8657'],
 ['WNG', ' Wingst', 2019, 2913, 53.74, '9.07'],
 ['AIA',
  ' Argentine Islands (Akademik Vernadsky base)',
  2019,
  2914,
  -65.25,
  -64.25],
 ['API', ' Apia', 2019, 2915, -13.8, -171.78],
 ['ASP', ' Alice Springs', 2019, 2916, -23.77, '133.88'],
 ['CKI', ' Cocos-Keeling Islands', 2019, 2917, -12.1875, '96.8336'],
 ['CNB', ' Canberra', 2019, 2918, -35.32, '149.36'],
 ['CSY', ' Casey Station', 2019, 2919, -66.283, '110.533'],
 ['CTA', ' Charters Towers', 2019, 2920, -20.1, '146.3'],
 ['DMC', ' Dome C', 2019, 2921, -75.25, '124.167'],
 ['DRV', " Dumont d'Urville", 2019, 2922, -66.67, '140.01'],
 ['EYR', ' Eyrewell', 2019, 2923, -43.474, '172.393'],
 ['GNG', ' Gingin', 2019, 2924, -31.356, '115.715'],
 ['GUA', ' Guam', 2019, 2925, 13.59, '144.87'],
 ['HON', ' Honolulu', 2019, 2926, 21.32, -158.0],
 ['KDU', ' Kakadu', 2019, 2927, -12.69, '132.47'],
 ['LRM', ' Learmonth', 2019, 2928, -22.22, '114.1'],
 ['MAW', ' Mawson', 2019, 2929, -67.6, '62.88'],
 ['MCQ', ' Macquarie Island', 2019, 2930, -54.5, '158.95'],
 ['PPT', ' Pamatai', 2019, 2931, -17.57, -149.58],
 ['SBA', ' Scott Base', 2019, 2932, -77.85, '166.78'],
 ['VNA', ' Neumayer Station Ⅲ', 2019, 2933, -70.683, -8.281999999999982],
 ['VOS', ' Vostok', 2019, 2934, -78.464, '106.835']]

In [ ]:
def sortss(oobs):
    arr = copy.deepcopy(oobs)
    for i in range(len(arr)-1):
        for j in range(len(arr)-i):
            if(arr[j]>arr[j+1]):
                arr[j][4], arr[j+1][4] = arr[j+1][4], arr[j][4]